export type SessionDetailsType = {
    activity : string,
    endtime : string,
    sessionid : string,
    sessiontime : number,
    shotsleft : number,
    shotsoverhandleft : number,
    shotsoverhandright : number,
    shotsright : number,
    shotssidearmleft : number,
    shotssidearmright : number,
    shotsunderhandleft : number,
    shotsunderhandright : number,
    sport: string,
    starttime : string,
    topspeed : string,
    totalshots : number,
    url : string,
}